//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityLog
    {
        public int ActivityLogID { get; set; }
        public Nullable<System.DateTime> Occured { get; set; }
        public string UserIP { get; set; }
        public string Username { get; set; }
        public string URI { get; set; }
        public string Method { get; set; }
        public string Payload { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
    }
}
