//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentOrderStatusDetailMapping
    {
        public int AgentOrderStatusDetailMappingId { get; set; }
        public int UserId { get; set; }
        public int OrderStatusDetailId { get; set; }
        public bool IsPublished { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedByUserId { get; set; }
    
        public virtual OrderStatusDetail OrderStatusDetail { get; set; }
        public virtual User User { get; set; }
    }
}
