//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BulkStatusCode
    {
        public int BulkStatusCodeId { get; set; }
        public string Key { get; set; }
        public string Description { get; set; }
        public Nullable<int> OrderStatusDetailId { get; set; }
        public Nullable<int> CampaignId { get; set; }
        public bool Active { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsPublished { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
        public Nullable<System.DateTime> UpdatedOnDate { get; set; }
    
        public virtual Campaign Campaign { get; set; }
        public virtual OrderStatusDetail OrderStatusDetail { get; set; }
    }
}
