//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BulkDealUploadContent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BulkDealUploadContent()
        {
            this.BulkDealUploadCampaigns = new HashSet<BulkDealUploadCampaign>();
            this.BulkDealUploadProducts = new HashSet<BulkDealUploadProduct>();
        }
    
        public int BulkDealUploadContentsId { get; set; }
        public int BulkDealUploadId { get; set; }
        public string DealCode { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> TariffId { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> GP { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public bool IsPublished { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<bool> Processed { get; set; }
        public Nullable<int> CampaignId { get; set; }
        public bool Multiple { get; set; }
        public Nullable<bool> IsInsurable { get; set; }
    
        public virtual Campaign Campaign { get; set; }
        public virtual BulkDealUpload BulkDealUpload { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BulkDealUploadCampaign> BulkDealUploadCampaigns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BulkDealUploadProduct> BulkDealUploadProducts { get; set; }
    }
}
