//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BulkStatusFileUpload
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BulkStatusFileUpload()
        {
            this.BulkStatusFileUploadContents = new HashSet<BulkStatusFileUploadContent>();
        }
    
        public int BulkStatusFileUploadID { get; set; }
        public System.DateTime UploadDate { get; set; }
        public int CampaignId { get; set; }
        public string Filename { get; set; }
        public int UploadUserId { get; set; }
        public bool CheckFile { get; set; }
    
        public virtual Campaign Campaign { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BulkStatusFileUploadContent> BulkStatusFileUploadContents { get; set; }
    }
}
