//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BundleDealMapping
    {
        public int BundleDealMappingId { get; set; }
        public int BundleId { get; set; }
        public int DealId { get; set; }
        public Nullable<decimal> DealAmount { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<int> ModifiedUserId { get; set; }
        public Nullable<System.DateTime> DbInsertedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsPublished { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Bundle Bundle { get; set; }
        public virtual Deal Deal { get; set; }
    }
}
