//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignSetting
    {
        public int CampaignSettingsId { get; set; }
        public int CampaignID { get; set; }
        public Nullable<decimal> BasketLimit { get; set; }
        public Nullable<bool> RequiresEmployment { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
        public Nullable<System.DateTime> UpdatedOnDate { get; set; }
        public bool IsPublished { get; set; }
        public bool IsDeleted { get; set; }
        public int VettingType { get; set; }
        public bool RequiresAddress { get; set; }
        public bool RequiresMaritalStatus { get; set; }
        public bool RequiresRelativeDetails { get; set; }
        public bool RequiresVerifier { get; set; }
        public bool RequiresNetCash { get; set; }
        public bool RequiresReferralCapture { get; set; }
        public bool DuplicateVASCheck { get; set; }
        public Nullable<int> ExergyCommissionOwnerId { get; set; }
        public bool RequiresAffordability { get; set; }
        public Nullable<int> AffordabilityMinimum { get; set; }
        public Nullable<int> AquaClientId { get; set; }
        public bool AllowBillLimitOverride { get; set; }
    
        public virtual ExergyCommissionOwner ExergyCommissionOwner { get; set; }
        public virtual Campaign Campaign { get; set; }
    }
}
