//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaign
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Campaign()
        {
            this.BulkStatusCodes = new HashSet<BulkStatusCode>();
            this.RELComissionOwnerCompanies = new HashSet<RELComissionOwnerCompany>();
            this.AspNetUsers = new HashSet<AspNetUser>();
            this.BulkDealUploadContents = new HashSet<BulkDealUploadContent>();
            this.CampaignIdentificationMappings = new HashSet<CampaignIdentificationMapping>();
            this.CampaignPayMethodMappings = new HashSet<CampaignPayMethodMapping>();
            this.BulkStatusFileUploads = new HashSet<BulkStatusFileUpload>();
            this.ProviderSalesExclusions = new HashSet<ProviderSalesExclusion>();
            this.AvsrHistories = new HashSet<AvsrHistory>();
            this.AvsrSettings = new HashSet<AvsrSetting>();
            this.BundleCampaignMappings = new HashSet<BundleCampaignMapping>();
            this.CampaignBrands = new HashSet<CampaignBrand>();
            this.CampaignDebitDays = new HashSet<CampaignDebitDay>();
            this.CampaignLeads = new HashSet<CampaignLead>();
            this.CampaignLeadConfigurations = new HashSet<CampaignLeadConfiguration>();
            this.CampaignLeadDetails = new HashSet<CampaignLeadDetail>();
            this.CampaignSettings = new HashSet<CampaignSetting>();
            this.CampaignTeams = new HashSet<CampaignTeam>();
            this.CampaignVerifiers = new HashSet<CampaignVerifier>();
            this.DealCampaigns = new HashSet<DealCampaign>();
            this.DialerLeads = new HashSet<DialerLead>();
            this.DialerMaps = new HashSet<DialerMap>();
            this.InstantAVSChecks = new HashSet<InstantAVSCheck>();
            this.Leads = new HashSet<Lead>();
            this.LeadTypes = new HashSet<LeadType>();
            this.Orders = new HashSet<Order>();
            this.OrderCancelReasonDetailCampaignMappings = new HashSet<OrderCancelReasonDetailCampaignMapping>();
            this.QACampaignConfigs = new HashSet<QACampaignConfig>();
            this.QACampaignQuestions = new HashSet<QACampaignQuestion>();
            this.QARatioLevelMappings = new HashSet<QARatioLevelMapping>();
            this.UserCampaignMappings = new HashSet<UserCampaignMapping>();
            this.VASExclusions = new HashSet<VASExclusion>();
            this.VASExclusionHistories = new HashSet<VASExclusionHistory>();
            this.VettingSettings = new HashSet<VettingSetting>();
        }
    
        public int CampaignID { get; set; }
        public string Title { get; set; }
        public Nullable<int> Active { get; set; }
        public string Code { get; set; }
        public string DialerDB { get; set; }
        public Nullable<bool> SequentialQA { get; set; }
        public Nullable<bool> LockLeads { get; set; }
        public Nullable<int> BrandId { get; set; }
        public string Script { get; set; }
        public int LeadManagementType { get; set; }
        public Nullable<int> QARatio { get; set; }
        public Nullable<int> NonSalesQARatio { get; set; }
        public Nullable<int> SupervisorQARatio { get; set; }
        public Nullable<int> AuditQARatio { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
        public Nullable<System.DateTime> UpdatedOnDate { get; set; }
        public bool IsPublished { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Brand Brand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BulkStatusCode> BulkStatusCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RELComissionOwnerCompany> RELComissionOwnerCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BulkDealUploadContent> BulkDealUploadContents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampaignIdentificationMapping> CampaignIdentificationMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampaignPayMethodMapping> CampaignPayMethodMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BulkStatusFileUpload> BulkStatusFileUploads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProviderSalesExclusion> ProviderSalesExclusions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvsrHistory> AvsrHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvsrSetting> AvsrSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BundleCampaignMapping> BundleCampaignMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampaignBrand> CampaignBrands { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampaignDebitDay> CampaignDebitDays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampaignLead> CampaignLeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampaignLeadConfiguration> CampaignLeadConfigurations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampaignLeadDetail> CampaignLeadDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampaignSetting> CampaignSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampaignTeam> CampaignTeams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampaignVerifier> CampaignVerifiers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DealCampaign> DealCampaigns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DialerLead> DialerLeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DialerMap> DialerMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstantAVSCheck> InstantAVSChecks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lead> Leads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeadType> LeadTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderCancelReasonDetailCampaignMapping> OrderCancelReasonDetailCampaignMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QACampaignConfig> QACampaignConfigs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QACampaignQuestion> QACampaignQuestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QARatioLevelMapping> QARatioLevelMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserCampaignMapping> UserCampaignMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VASExclusion> VASExclusions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VASExclusionHistory> VASExclusionHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VettingSetting> VettingSettings { get; set; }
    }
}
