//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignPayMethodMapping
    {
        public int CampaignPayMethodMappingId { get; set; }
        public int PayMethodID { get; set; }
        public int CampaignID { get; set; }
    
        public virtual PayMethod PayMethod { get; set; }
        public virtual Campaign Campaign { get; set; }
    }
}
