//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommunicationTemplate
    {
        public int CommunicationTemplateId { get; set; }
        public int UserId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int CommunicationMethodId { get; set; }
        public string Name { get; set; }
        public string ContentType { get; set; }
        public string Template { get; set; }
    
        public virtual CommuncationMethod CommuncationMethod { get; set; }
        public virtual User User { get; set; }
    }
}
