//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourierConfig
    {
        public int CourierConfigID { get; set; }
        public int BrandID { get; set; }
        public string ServiceCode { get; set; }
        public string SpecialInstructions { get; set; }
        public int CourierIT { get; set; }
        public int RAM { get; set; }
        public int Rica { get; set; }
        public Nullable<int> NewInvoice { get; set; }
        public int DawnWing { get; set; }
    }
}
