//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAttachment
    {
        public long CustomerAttachmentId { get; set; }
        public int CustomerId { get; set; }
        public string FilePath { get; set; }
        public string FileName { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> DateUploaded { get; set; }
        public Nullable<int> RootFolderId { get; set; }
        public Nullable<int> Folder { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
        public Nullable<System.DateTime> UpdatedOnDate { get; set; }
        public bool IsPublished { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual CustomerAttRoot CustomerAttRoot { get; set; }
    }
}
