//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerEmployment
    {
        public int CustomerEmploymentId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string EmployerName { get; set; }
        public string EmployerContact { get; set; }
        public Nullable<System.DateTime> EmploymentStart { get; set; }
        public Nullable<int> EmploymentTypeId { get; set; }
        public Nullable<decimal> Gross { get; set; }
        public Nullable<decimal> Net { get; set; }
        public Nullable<int> PayDay { get; set; }
        public Nullable<int> Occupation { get; set; }
        public string Department { get; set; }
        public string Branch { get; set; }
        public Nullable<int> CityId { get; set; }
        public string Street { get; set; }
        public string StreetNum { get; set; }
        public string Unit { get; set; }
        public Nullable<int> PostCode { get; set; }
        public string SupervisorName { get; set; }
        public string CompanyName { get; set; }
        public Nullable<System.DateTime> ContractExpiryDate { get; set; }
        public Nullable<decimal> AdditionalIncome { get; set; }
        public Nullable<decimal> MonthlyExpenses { get; set; }
        public string EmploymentTerm { get; set; }
        public Nullable<int> CustomerEmploymentAccountabilityId { get; set; }
        public Nullable<int> CustomerPaymentFrequencyId { get; set; }
        public Nullable<bool> Latest { get; set; }
        public int EmploymentPeriod { get; set; }
        public int CustomerType { get; set; }
        public Nullable<int> IndustryId { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
        public Nullable<System.DateTime> UpdatedOnDate { get; set; }
        public bool IsPublished { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual City City { get; set; }
        public virtual ClientType ClientType { get; set; }
        public virtual CurrentPeriodEmployed CurrentPeriodEmployed { get; set; }
        public virtual Industry Industry { get; set; }
        public virtual Profession Profession { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual CustomerEmploymentAccountability CustomerEmploymentAccountability { get; set; }
        public virtual CustomerPaymentFrequency CustomerPaymentFrequency { get; set; }
        public virtual EmpType EmpType { get; set; }
    }
}
