//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerBank
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerBank()
        {
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public int CustomerBankId { get; set; }
        public int CustomerId { get; set; }
        public Nullable<int> BankId { get; set; }
        public Nullable<int> BankAccountTypeId { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<int> BranchCodeId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public int PayMethodId { get; set; }
        public Nullable<int> MsId { get; set; }
        public Nullable<int> EmId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> DebitDate { get; set; }
        public Nullable<int> BankRef { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
        public Nullable<System.DateTime> UpdatedOnDate { get; set; }
        public bool IsPublished { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual BankAccountType BankAccountType { get; set; }
        public virtual BankBranch BankBranch { get; set; }
        public virtual PayMethod PayMethod { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }
    }
}
