//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAddressArchive
    {
        public int CustomerAddressArchiveId { get; set; }
        public int CustomerId { get; set; }
        public int AddressTypeId { get; set; }
        public Nullable<int> ResIdenceTypeId { get; set; }
        public int CityId { get; set; }
        public string Company { get; set; }
        public int ProvinceId { get; set; }
        public string Notes { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string Suburb { get; set; }
        public string StreetName { get; set; }
        public string StreetNum { get; set; }
        public string Building { get; set; }
        public int PostCode { get; set; }
        public System.DateTime DateArchived { get; set; }
        public int ArchivedBy { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
        public Nullable<System.DateTime> UpdatedOnDate { get; set; }
        public bool IsPublished { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual AddressType AddressType { get; set; }
        public virtual City City { get; set; }
        public virtual Province Province { get; set; }
        public virtual ResidenceType ResidenceType { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
