//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealNotFound
    {
        public int DealNotFoundId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> OrdermasterId { get; set; }
        public Nullable<int> OrderItemNumber { get; set; }
        public Nullable<int> OrderType { get; set; }
        public Nullable<long> OrderCommission { get; set; }
        public string OrderCommissionAmount { get; set; }
        public Nullable<long> OrderHold { get; set; }
        public string OrderHoldReason { get; set; }
        public string OrderPrefix { get; set; }
        public Nullable<long> OrderCancel { get; set; }
        public string OrderCancelReason { get; set; }
        public Nullable<byte> OrderStatusQv { get; set; }
        public Nullable<long> OrderStatusQvPdt { get; set; }
        public Nullable<int> DealId { get; set; }
        public Nullable<int> StatDetailId { get; set; }
        public Nullable<long> BankingId { get; set; }
    }
}
