//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DialerLead
    {
        public int DialerLeadId { get; set; }
        public string IDNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public Nullable<int> UploadUserId { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public Nullable<int> LeadBatchId { get; set; }
        public Nullable<int> CampaignID { get; set; }
    
        public virtual Campaign Campaign { get; set; }
        public virtual LeadBatch LeadBatch { get; set; }
        public virtual User User { get; set; }
    }
}
