//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExergyCommissionOwner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExergyCommissionOwner()
        {
            this.CampaignSettings = new HashSet<CampaignSetting>();
            this.RELComissionOwnerCompanies = new HashSet<RELComissionOwnerCompany>();
        }
    
        public int ExergyCommissionOwnerId { get; set; }
        public string BrokerCode { get; set; }
        public int CampaignCode { get; set; }
        public string CampaignTypeCode { get; set; }
        public int StrategyDescriptionId { get; set; }
        public int DistributionContractDescriptionId { get; set; }
        public int Percentage { get; set; }
        public int CreatedByUserId { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsPublished { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
        public Nullable<System.DateTime> UpdatedOnDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampaignSetting> CampaignSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RELComissionOwnerCompany> RELComissionOwnerCompanies { get; set; }
    }
}
