//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feature
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Feature()
        {
            this.FeatureInRoles = new HashSet<FeatureInRole>();
        }
    
        public int FeatureId { get; set; }
        public int FeatureCategoryID { get; set; }
        public int Ordering { get; set; }
        public bool Display { get; set; }
        public string Name { get; set; }
        public string RoutePath { get; set; }
        public string HTTPMethod { get; set; }
        public bool AllowAnonymous { get; set; }
        public string QueryString { get; set; }
        public Nullable<bool> IsReport { get; set; }
        public string Description { get; set; }
        public string Target { get; set; }
        public Nullable<bool> IsExternalAddress { get; set; }
    
        public virtual FeatureCategory FeatureCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeatureInRole> FeatureInRoles { get; set; }
    }
}
