//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeadType
    {
        public int LeadTypeID { get; set; }
        public string Name { get; set; }
        public Nullable<int> CampaignId { get; set; }
    
        public virtual Campaign Campaign { get; set; }
    }
}
