//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeadField
    {
        public long LeadFieldId { get; set; }
        public int LeadId { get; set; }
        public int ElementId { get; set; }
        public int Index { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
    
        public virtual Lead Lead { get; set; }
        public virtual LeadUploadElement LeadUploadElement { get; set; }
    }
}
