//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lead
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lead()
        {
            this.DistributionLogs = new HashSet<DistributionLog>();
            this.CampaignLeads = new HashSet<CampaignLead>();
            this.SMSSents = new HashSet<SMSSent>();
            this.LeadContacts = new HashSet<LeadContact>();
            this.LeadFields = new HashSet<LeadField>();
            this.LeadStatusHistories = new HashSet<LeadStatusHistory>();
        }
    
        public int LeadID { get; set; }
        public Nullable<int> LeadStatusDetailId { get; set; }
        public Nullable<System.DateTime> AllocationDate { get; set; }
        public Nullable<int> AllocationUserID { get; set; }
        public string IDNumber { get; set; }
        public string MobileNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> UploadUserId { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public Nullable<int> LeadBatchId { get; set; }
        public Nullable<int> CampaignID { get; set; }
        public Nullable<System.DateTime> CallBackDate { get; set; }
        public Nullable<int> CallBackCount { get; set; }
        public string MobileNumber1 { get; set; }
        public string MobileNumber2 { get; set; }
        public string MobileNumber3 { get; set; }
        public Nullable<decimal> MonthlyAverage { get; set; }
        public string Comment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DistributionLog> DistributionLogs { get; set; }
        public virtual Campaign Campaign { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampaignLead> CampaignLeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMSSent> SMSSents { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeadContact> LeadContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeadField> LeadFields { get; set; }
        public virtual LeadBatch LeadBatch { get; set; }
        public virtual LeadStatusDetail LeadStatusDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeadStatusHistory> LeadStatusHistories { get; set; }
        public virtual User User1 { get; set; }
    }
}
