//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeadContact
    {
        public int LeadContactId { get; set; }
        public int LeadId { get; set; }
        public string Contact { get; set; }
        public int ContactTypeId { get; set; }
        public Nullable<bool> Latest { get; set; }
    
        public virtual ContactType ContactType { get; set; }
        public virtual Lead Lead { get; set; }
    }
}
