//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeadUploadFormatElement
    {
        public int LeadUploadFormatElementId { get; set; }
        public int LeadUploadFormatId { get; set; }
        public int LeadUploadElementId { get; set; }
    
        public virtual LeadUploadElement LeadUploadElement { get; set; }
        public virtual LeadUploadFormat LeadUploadFormat { get; set; }
    }
}
