//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MigrationUserType
    {
        public int MigrationUserTypesId { get; set; }
        public Nullable<int> MSUserType { get; set; }
        public Nullable<int> PromUsertype { get; set; }
    }
}
