//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MigrationStatusMapping
    {
        public int MigrationStatusMappingID { get; set; }
        public int StatusMSID { get; set; }
        public int StatusMapID { get; set; }
        public int StatusDetailMSID { get; set; }
        public int StatusDetailMapId { get; set; }
    }
}
