//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MigratAddressError
    {
        public int MigratAddressErrorId { get; set; }
        public Nullable<int> AddressId { get; set; }
        public string AddressTypeTitle { get; set; }
        public string Unit { get; set; }
        public string Building { get; set; }
        public string Company { get; set; }
        public string Street { get; set; }
        public string Suburb { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public Nullable<int> CustId { get; set; }
        public Nullable<int> AddressTypeId { get; set; }
        public Nullable<int> ProvinceId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> PostCode { get; set; }
        public Nullable<int> ResidenceType { get; set; }
        public Nullable<int> Code { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<int> ErrorCode { get; set; }
        public Nullable<int> ErrorColumn { get; set; }
    }
}
