//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NonSalesCustomerOptIn
    {
        public int NonSalesCustomerOptInId { get; set; }
        public int NonSalesCustomerId { get; set; }
        public int OptInTypeId { get; set; }
        public int OptInValueId { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
        public Nullable<System.DateTime> UpdatedOnDate { get; set; }
        public bool IsPublished { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual NonSalesCustomer NonSalesCustomer { get; set; }
        public virtual OptInType OptInType { get; set; }
        public virtual OptInValue OptInValue { get; set; }
    }
}
