//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationsProviderSpecificQueue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OperationsProviderSpecificQueue()
        {
            this.RetentionProviderStatusMappings = new HashSet<RetentionProviderStatusMapping>();
        }
    
        public int OperationsProviderSpecificQueueId { get; set; }
        public string OperationsProviderSpecificName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RetentionProviderStatusMapping> RetentionProviderStatusMappings { get; set; }
    }
}
