//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDelivery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderDelivery()
        {
            this.OrderDeliverySlots = new HashSet<OrderDeliverySlot>();
        }
    
        public int OrderDeliveryId { get; set; }
        public int OrderItemId { get; set; }
        public int CustomerAddressId { get; set; }
        public Nullable<int> DeliveryTypeId { get; set; }
        public Nullable<int> DispatchWayBillNumber { get; set; }
        public Nullable<System.DateTime> DispatchDate { get; set; }
        public Nullable<int> OrderStatusDetailId { get; set; }
        public string WayBillNumber { get; set; }
        public Nullable<int> FastTrackerNumber { get; set; }
        public Nullable<System.DateTime> EstimateDeliveryDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string Directions { get; set; }
        public string IMEI { get; set; }
        public string OrderNumber { get; set; }
        public string DeliveryNote { get; set; }
        public string PackageStatus { get; set; }
        public string ReleaseForDespatch { get; set; }
        public string PaymentRef { get; set; }
        public string ConsignedFlag { get; set; }
        public string RTS { get; set; }
        public string RTSReason { get; set; }
        public string RTSNote { get; set; }
        public string ConsignmentID { get; set; }
    
        public virtual DeliveryType DeliveryType { get; set; }
        public virtual CustomerAddress CustomerAddress { get; set; }
        public virtual OrderItem OrderItem { get; set; }
        public virtual OrderStatusDetail OrderStatusDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDeliverySlot> OrderDeliverySlots { get; set; }
    }
}
