//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderActive
    {
        public int OrderActiveID { get; set; }
        public Nullable<long> OrderItemId { get; set; }
        public string NetworkOrderRef { get; set; }
        public Nullable<long> NetworkCustomerID { get; set; }
        public string NetworkMSISDN { get; set; }
        public string Comment { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
