//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItemError
    {
        public int OrderItemErrorId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> OrdermasterId { get; set; }
        public Nullable<int> OrderItemNumber { get; set; }
        public Nullable<int> OrderType { get; set; }
        public Nullable<long> OrderCommission { get; set; }
        public string OrderCommissionAmount { get; set; }
        public Nullable<long> OrderHold { get; set; }
        public string OrderHoldReason { get; set; }
        public string OrderPrefix { get; set; }
        public Nullable<long> OrderCancel { get; set; }
        public string OrderCancelReason { get; set; }
        public Nullable<byte> OrderStatusQv { get; set; }
        public Nullable<long> OrderStatusQvPdt { get; set; }
        public Nullable<int> DealId { get; set; }
        public Nullable<int> StatDetailId { get; set; }
        public Nullable<long> BankingId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> StatusDetailId { get; set; }
        public Nullable<int> CustomerBankId { get; set; }
        public string OrderReference { get; set; }
        public Nullable<int> SMSSent { get; set; }
        public Nullable<int> FaxSent { get; set; }
        public Nullable<int> DocumentationCompleted { get; set; }
        public Nullable<int> RICAIndicator { get; set; }
        public Nullable<int> ItemEscalation { get; set; }
        public Nullable<int> BuyOut { get; set; }
        public Nullable<int> ErrorCode { get; set; }
        public Nullable<int> ErrorColumn { get; set; }
    }
}
