//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderProviderStatusCommsTemplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderProviderStatusCommsTemplate()
        {
            this.OrderProviderStatusCommsTemplateHistories = new HashSet<OrderProviderStatusCommsTemplateHistory>();
        }
    
        public int OrderProviderStatusCommsTemplateId { get; set; }
        public int ProvIderId { get; set; }
        public int OrderStatusDetailId { get; set; }
        public string EmailTemplateURL { get; set; }
        public string SMSTemplateText { get; set; }
        public string EmailSubject { get; set; }
        public string EmailSourceAddress { get; set; }
        public string ViewEmailSourceAddress { get; set; }
        public int PayMethodId { get; set; }
        public string EmailTemplateName { get; set; }
    
        public virtual PayMethod PayMethod { get; set; }
        public virtual Provider Provider { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProviderStatusCommsTemplateHistory> OrderProviderStatusCommsTemplateHistories { get; set; }
        public virtual OrderStatusDetail OrderStatusDetail { get; set; }
    }
}
