//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStatusDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderStatusDetail()
        {
            this.BulkStatusCodes = new HashSet<BulkStatusCode>();
            this.ProviderStatusMappings = new HashSet<ProviderStatusMapping>();
            this.AgentOrderStatusDetailMappings = new HashSet<AgentOrderStatusDetailMapping>();
            this.RetentionProviderStatusMappings = new HashSet<RetentionProviderStatusMapping>();
            this.RetentionProviderStatusMappings1 = new HashSet<RetentionProviderStatusMapping>();
            this.RetentionProviderStatusMappings2 = new HashSet<RetentionProviderStatusMapping>();
            this.RetentionProviderStatusMappings3 = new HashSet<RetentionProviderStatusMapping>();
            this.OrderBundles = new HashSet<OrderBundle>();
            this.OrderConfirmationTemplates = new HashSet<OrderConfirmationTemplate>();
            this.OrderDeliveries = new HashSet<OrderDelivery>();
            this.OrderItems = new HashSet<OrderItem>();
            this.OrderProviderStatusCommsTemplates = new HashSet<OrderProviderStatusCommsTemplate>();
            this.OrderStatusHistories = new HashSet<OrderStatusHistory>();
            this.RetensionsOrderStatusQueues = new HashSet<RetensionsOrderStatusQueue>();
        }
    
        public int OrderStatusDetailID { get; set; }
        public string StatusDetailText { get; set; }
        public int OrderStatusId { get; set; }
        public Nullable<int> MsId { get; set; }
        public Nullable<int> EMId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BulkStatusCode> BulkStatusCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProviderStatusMapping> ProviderStatusMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgentOrderStatusDetailMapping> AgentOrderStatusDetailMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RetentionProviderStatusMapping> RetentionProviderStatusMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RetentionProviderStatusMapping> RetentionProviderStatusMappings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RetentionProviderStatusMapping> RetentionProviderStatusMappings2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RetentionProviderStatusMapping> RetentionProviderStatusMappings3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderBundle> OrderBundles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderConfirmationTemplate> OrderConfirmationTemplates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDelivery> OrderDeliveries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProviderStatusCommsTemplate> OrderProviderStatusCommsTemplates { get; set; }
        public virtual OrderStatu OrderStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderStatusHistory> OrderStatusHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RetensionsOrderStatusQueue> RetensionsOrderStatusQueues { get; set; }
    }
}
