//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderRetention
    {
        public int OrderRetentionId { get; set; }
        public int OrderItemId { get; set; }
        public string ReplaceOrder { get; set; }
        public string ChangePackage { get; set; }
        public int InitialDealId { get; set; }
        public string InitialOrderNumber { get; set; }
        public string VASRetention { get; set; }
    
        public virtual Deal Deal { get; set; }
        public virtual OrderItem OrderItem { get; set; }
    }
}
