//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItemData
    {
        public int OrderItemDataId { get; set; }
        public int OrderItemId { get; set; }
        public string AccountNumber { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string ActivationNumber { get; set; }
        public Nullable<bool> RICA { get; set; }
        public Nullable<int> ItemisedBillingTypeId { get; set; }
        public Nullable<int> StockItemId { get; set; }
        public Nullable<bool> IsActivated { get; set; }
        public string Token { get; set; }
        public string Voucher { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public int CommSentStatus { get; set; }
        public int EmailCommSent { get; set; }
        public Nullable<int> OrderBillingStatusId { get; set; }
    
        public virtual CommSentStatu CommSentStatu { get; set; }
        public virtual CommSentStatu CommSentStatu1 { get; set; }
        public virtual OrderBillingStatu OrderBillingStatu { get; set; }
        public virtual OrderItem OrderItem { get; set; }
        public virtual StockItem StockItem { get; set; }
    }
}
