//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderProviderStatusCommsTemplateHistory
    {
        public int OrderProviderStatusCommsTemplateHistoryId { get; set; }
        public int TemplateId { get; set; }
        public string Annotation { get; set; }
        public int UserId { get; set; }
        public System.DateTime Occured { get; set; }
    
        public virtual OrderProviderStatusCommsTemplate OrderProviderStatusCommsTemplate { get; set; }
        public virtual User User { get; set; }
    }
}
