//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderBundle
    {
        public int OrderBundleId { get; set; }
        public int OrderId { get; set; }
        public int BundleId { get; set; }
        public int OrderStatusDetailId { get; set; }
        public int CommsSentStatusId { get; set; }
        public int EmailSentStatusId { get; set; }
        public int CreatedByUserId { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsPublished { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
        public Nullable<System.DateTime> UpdatedOnDate { get; set; }
    
        public virtual Bundle Bundle { get; set; }
        public virtual CommSentStatu CommSentStatu { get; set; }
        public virtual CommSentStatu CommSentStatu1 { get; set; }
        public virtual Order Order { get; set; }
        public virtual OrderStatusDetail OrderStatusDetail { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
