//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderAnnotation
    {
        public int OrderAnnotationId { get; set; }
        public int OrderItemId { get; set; }
        public int UserId { get; set; }
        public System.DateTime AnnotationDate { get; set; }
        public string Details { get; set; }
        public int AnnotationTypeId { get; set; }
    
        public virtual OrderItem OrderItem { get; set; }
        public virtual User User { get; set; }
    }
}
