//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderConfirmationTemplate
    {
        public int OrderConfirmationTemplateId { get; set; }
        public int BrandId { get; set; }
        public int OrderStatusDetailId { get; set; }
        public string EmailTemplateURL { get; set; }
        public string SMSTemplateText { get; set; }
        public string EmailSubject { get; set; }
        public string EmailSourceAddress { get; set; }
        public string ViewEmailSourceAddress { get; set; }
        public bool Active { get; set; }
        public string EmailTemplateName { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual OrderStatusDetail OrderStatusDetail { get; set; }
    }
}
