//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderVetting
    {
        public int OrderVettingId { get; set; }
        public int OrderId { get; set; }
        public string ExistingCustomer { get; set; }
        public string Vetter { get; set; }
        public string VettingAccountNumber { get; set; }
        public string QuoteNumber { get; set; }
        public string ClaimNumber { get; set; }
        public string Originals { get; set; }
        public Nullable<System.DateTime> OriginalsSentDate { get; set; }
        public string PreApprovalDecline { get; set; }
        public string NotPreApprovedNotes { get; set; }
        public decimal RiskRating { get; set; }
        public int NumChild { get; set; }
        public int NumParent { get; set; }
        public string StepUp { get; set; }
        public string StepUpLink { get; set; }
        public int PortfolioId { get; set; }
        public Nullable<System.DateTime> FraudDate { get; set; }
        public Nullable<int> RSNo { get; set; }
        public string ProviderAgent { get; set; }
        public int SupplierId { get; set; }
        public string SPINumber { get; set; }
        public string Notes { get; set; }
    
        public virtual Portfolio Portfolio { get; set; }
        public virtual Order Order { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
