//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStatusHistory
    {
        public int OrderStatusHistoryId { get; set; }
        public int OrderItemId { get; set; }
        public System.DateTime Occured { get; set; }
        public string Annotation { get; set; }
        public int OrderStatusDetailId { get; set; }
        public Nullable<int> OrderCancelReasonDetailId { get; set; }
        public Nullable<int> CancelStatusDetailId { get; set; }
        public int EmailCommSentStatusId { get; set; }
        public int SMSCommSentStatusId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual CommSentStatu CommSentStatu { get; set; }
        public virtual CommSentStatu CommSentStatu1 { get; set; }
        public virtual OrderCancelReasonDetail OrderCancelReasonDetail { get; set; }
        public virtual OrderItem OrderItem { get; set; }
        public virtual OrderStatusDetail OrderStatusDetail { get; set; }
        public virtual User User { get; set; }
    }
}
