//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderType
    {
        public int OrderTypeID { get; set; }
        public string OrderType1 { get; set; }
        public Nullable<int> OldMsId { get; set; }
        public Nullable<int> OldEmId { get; set; }
    }
}
