//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PleexProviderSpecific
    {
        public int PleexProviderSpecificId { get; set; }
        public int OrderItemId { get; set; }
        public int PleexDeviceId { get; set; }
    
        public virtual PleexDeviceList PleexDeviceList { get; set; }
        public virtual OrderItem OrderItem { get; set; }
    }
}
