//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PortingProviderSpecific
    {
        public int PortingProviderSpecificId { get; set; }
        public int OrderItemId { get; set; }
        public string PortMSISDN { get; set; }
        public int NetworkId { get; set; }
        public int PortAccountPayMethodId { get; set; }
        public string AccountNumber { get; set; }
        public int PortAccountTypeId { get; set; }
        public string RegistrationNumber { get; set; }
        public string ContactPerson { get; set; }
        public string ContactPersonNumber { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsPublished { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
        public Nullable<System.DateTime> UpdatedOnDate { get; set; }
    
        public virtual Network Network { get; set; }
        public virtual PortAccountPayMethod PortAccountPayMethod { get; set; }
        public virtual PortAccountType PortAccountType { get; set; }
        public virtual OrderItem OrderItem { get; set; }
    }
}
