//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.CategoryAttributeProductValues = new HashSet<CategoryAttributeProductValue>();
            this.DealProductMappings = new HashSet<DealProductMapping>();
            this.ProductPictures = new HashSet<ProductPicture>();
            this.StockItems = new HashSet<StockItem>();
        }
    
        public int ProductID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string WriteUp { get; set; }
        public int Active { get; set; }
        public Nullable<decimal> StockCount { get; set; }
        public string Barcode { get; set; }
        public int ManufacturerId { get; set; }
        public int CategoryId { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> OldProdId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryAttributeProductValue> CategoryAttributeProductValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DealProductMapping> DealProductMappings { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductPicture> ProductPictures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockItem> StockItems { get; set; }
    }
}
