//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderStatusMapping
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProviderStatusMapping()
        {
            this.ProviderStatusMapping1 = new HashSet<ProviderStatusMapping>();
        }
    
        public int ProviderStatusMappingId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int ProviderId { get; set; }
        public int OrderStatusDetailsId { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsPublished { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
        public Nullable<System.DateTime> UpdatedOnDate { get; set; }
    
        public virtual OrderStatusDetail OrderStatusDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProviderStatusMapping> ProviderStatusMapping1 { get; set; }
        public virtual ProviderStatusMapping ProviderStatusMapping2 { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
