//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderRangeDealMapping
    {
        public int ProviderRangeDealMappingId { get; set; }
        public Nullable<int> ProviderRangeId { get; set; }
        public Nullable<int> DealId { get; set; }
    
        public virtual ProviderRange ProviderRange { get; set; }
        public virtual Deal Deal { get; set; }
    }
}
