//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QAForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QAForm()
        {
            this.QACCQueries = new HashSet<QACCQuery>();
            this.QAOrders = new HashSet<QAOrder>();
            this.QAResponses = new HashSet<QAResponse>();
        }
    
        public int QAFormId { get; set; }
        public int OrderId { get; set; }
        public System.DateTime FormDate { get; set; }
        public int QAQuestionTypeId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> FormStatusId { get; set; }
        public Nullable<int> QueueItemId { get; set; }
        public string Comments { get; set; }
    
        public virtual Order Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QACCQuery> QACCQueries { get; set; }
        public virtual QAFormStatu QAFormStatu { get; set; }
        public virtual QAQuestionType QAQuestionType { get; set; }
        public virtual QAQueue QAQueue { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QAOrder> QAOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QAResponse> QAResponses { get; set; }
    }
}
