//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QALevel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QALevel()
        {
            this.QARatioLevelMappings = new HashSet<QARatioLevelMapping>();
            this.QARoleLevels = new HashSet<QARoleLevel>();
        }
    
        public int QALevelId { get; set; }
        public string Name { get; set; }
        public int QATypeId { get; set; }
        public int RoleId { get; set; }
        public int Position { get; set; }
    
        public virtual QAType QAType { get; set; }
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QARatioLevelMapping> QARatioLevelMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QARoleLevel> QARoleLevels { get; set; }
    }
}
