//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QANonSalesQueue
    {
        public int QANonSalesQueueId { get; set; }
        public int NonSalesCustomerId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateStarted { get; set; }
        public Nullable<int> UserId { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> DateFinished { get; set; }
        public Nullable<int> OriginalQAFormID { get; set; }
    
        public virtual NonSalesCustomer NonSalesCustomer { get; set; }
    }
}
