//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QAOrder
    {
        public int QAOrderId { get; set; }
        public int QAFormId { get; set; }
        public int OrderRecordingId { get; set; }
    
        public virtual OrderRecording OrderRecording { get; set; }
        public virtual QAForm QAForm { get; set; }
    }
}
