//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QAProgress
    {
        public int QAProgressId { get; set; }
        public int OrderId { get; set; }
        public int QuestionTypeId { get; set; }
        public int Complete { get; set; }
        public int UserId { get; set; }
        public string Recording { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual QAQuestionType QAQuestionType { get; set; }
        public virtual User User { get; set; }
    }
}
