//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QAQueue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QAQueue()
        {
            this.QAForms = new HashSet<QAForm>();
        }
    
        public int QAQueueId { get; set; }
        public int OrderId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int QAQuestionTypeId { get; set; }
        public Nullable<System.DateTime> DateStarted { get; set; }
        public Nullable<int> UserId { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> DateFinished { get; set; }
        public Nullable<int> OriginalQAFormID { get; set; }
    
        public virtual Order Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QAForm> QAForms { get; set; }
        public virtual QAQuestionType QAQuestionType { get; set; }
    }
}
