//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QAQuestionsFormTypeMapping
    {
        public int QAQuestionsFormTypeMappingId { get; set; }
        public int QAQuestionId { get; set; }
        public int QAQuestionTypeId { get; set; }
        public bool IsSelected { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsPublished { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
        public Nullable<System.DateTime> UpdatedOnDate { get; set; }
    
        public virtual QAQuestion QAQuestion { get; set; }
        public virtual QAQuestionType QAQuestionType { get; set; }
    }
}
