//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QARoleLevel
    {
        public int QARoleLevelId { get; set; }
        public int RoleId { get; set; }
        public int LevelId { get; set; }
    
        public virtual QALevel QALevel { get; set; }
        public virtual Role Role { get; set; }
    }
}
