//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetensionsOrderStatusQueue
    {
        public int RetensionsOrderStatusQueueId { get; set; }
        public int OrderId { get; set; }
        public Nullable<int> OrderItemId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public int OrderStatusDetailId { get; set; }
        public System.DateTime DateStarted { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsPublished { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
        public Nullable<System.DateTime> UpdatedOnDate { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual OrderItem OrderItem { get; set; }
        public virtual OrderStatusDetail OrderStatusDetail { get; set; }
    }
}
