//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleChangeLogging
    {
        public int RoleChangeLoggingId { get; set; }
        public string Description { get; set; }
        public int ChangeyByID { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public Nullable<int> FeatureId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
