//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleReferralResolution
    {
        public int SaleReferralResolutionId { get; set; }
        public int SaleReferralID { get; set; }
        public int CallbackResolutionID { get; set; }
        public int SalesUserID { get; set; }
        public System.DateTime DateOccured { get; set; }
    
        public virtual SaleReferralList SaleReferralList { get; set; }
    }
}
