//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleReferralList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SaleReferralList()
        {
            this.SaleReferralResolutions = new HashSet<SaleReferralResolution>();
        }
    
        public int SaleReferralListID { get; set; }
        public int AddedBy { get; set; }
        public Nullable<int> QAID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public int TeamLeadID { get; set; }
        public int Status { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public string Comment { get; set; }
    
        public virtual Order Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleReferralResolution> SaleReferralResolutions { get; set; }
    }
}
