//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleRuleDealMapping
    {
        public int SaleRuleDealMappingID { get; set; }
        public int SaleRuleId { get; set; }
        public int DealId { get; set; }
        public int MappedDealId { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
        public Nullable<System.DateTime> UpdatedOnDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual SaleRule SaleRule { get; set; }
        public virtual Deal Deal { get; set; }
        public virtual Deal Deal1 { get; set; }
    }
}
