//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSSent
    {
        public int SMSSentId { get; set; }
        public int UserId { get; set; }
        public int LeadId { get; set; }
        public int BrandId { get; set; }
        public int SMSInboxId { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
        public Nullable<System.DateTime> UpdatedOnDate { get; set; }
        public bool IsPublished { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual SMSInbox SMSInbox { get; set; }
        public virtual Lead Lead { get; set; }
        public virtual User User { get; set; }
    }
}
