//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoMusicProviderSpecific
    {
        public int SoMusicProviderSpecificId { get; set; }
        public int OrderItemId { get; set; }
        public Nullable<decimal> BasketTotal { get; set; }
        public Nullable<decimal> ProductPrice { get; set; }
        public string PaymentRef { get; set; }
        public string GiftWrapOccasion { get; set; }
        public string GiftWrapMsgTo { get; set; }
        public string GiftWrapMsgFrom { get; set; }
        public string GiftWrapMsg { get; set; }
        public bool IsPublished { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedByUserId { get; set; }
    
        public virtual OrderItem OrderItem { get; set; }
    }
}
