//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockPurchaseOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockPurchaseOrder()
        {
            this.StockItems = new HashSet<StockItem>();
            this.StockPurchaseOrderItems = new HashSet<StockPurchaseOrderItem>();
        }
    
        public int StockPurchaseOrderID { get; set; }
        public Nullable<int> PONumber { get; set; }
        public Nullable<int> ItemCount { get; set; }
        public Nullable<byte> Closed { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> SupplierId { get; set; }
    
        public virtual Brand Brand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockItem> StockItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockPurchaseOrderItem> StockPurchaseOrderItems { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
