//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockItem()
        {
            this.OrderItemDatas = new HashSet<OrderItemData>();
            this.StockItemOrderHistories = new HashSet<StockItemOrderHistory>();
            this.StockStatusHistories = new HashSet<StockStatusHistory>();
        }
    
        public int StockItemId { get; set; }
        public string SerialNumber { get; set; }
        public string Pin { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> StockPurchaseOrderId { get; set; }
        public Nullable<int> StockInvoiceId { get; set; }
        public int ProductId { get; set; }
        public Nullable<int> ReturnStatus { get; set; }
        public Nullable<int> BrandId { get; set; }
        public string SIM { get; set; }
        public Nullable<int> Received { get; set; }
        public Nullable<int> StockStatusId { get; set; }
        public Nullable<int> OrderItemId { get; set; }
        public string IMSI { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual OrderItem OrderItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItemData> OrderItemDatas { get; set; }
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockItemOrderHistory> StockItemOrderHistories { get; set; }
        public virtual StockPurchaseOrder StockPurchaseOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockStatusHistory> StockStatusHistories { get; set; }
    }
}
