//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockInvoice
    {
        public int StockInvoiceId { get; set; }
        public string InvoiceNo { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int UserId { get; set; }
        public string SupplierInvoiceNo { get; set; }
        public int StockPurchaseOrderId { get; set; }
    
        public virtual User User { get; set; }
    }
}
