//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierBrand
    {
        public int SupplierBrandId { get; set; }
        public int SupplierId { get; set; }
        public int BrandId { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
