//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierEmployeeIndustry
    {
        public int SupplierEmployeeIndustryId { get; set; }
        public int SupplierId { get; set; }
        public int EmployeeIndustryId { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        public virtual EmployeeIndustry EmployeeIndustry { get; set; }
    }
}
