//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierAccount
    {
        public int SupplierAccountId { get; set; }
        public int SupplierId { get; set; }
        public int BranchCodeId { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<int> AccountTypeId { get; set; }
    
        public virtual AccountType AccountType { get; set; }
        public virtual BankBranch BankBranch { get; set; }
    }
}
