//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamLead
    {
        public int TeamLeadId { get; set; }
        public Nullable<int> TeamId { get; set; }
        public Nullable<int> LeadBatchId { get; set; }
    
        public virtual LeadBatch LeadBatch { get; set; }
        public virtual Team Team { get; set; }
    }
}
