//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpSuburb
    {
        public int TmpSuburbId { get; set; }
        public int SuburbId { get; set; }
        public int CityId { get; set; }
        public string SuburbName { get; set; }
        public string PostCode1 { get; set; }
        public string PostCode2 { get; set; }
    }
}
