//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Token
    {
        public int TokenId { get; set; }
        public int UserID { get; set; }
        public Nullable<System.Guid> TokenValue { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
