//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackingProviderContact
    {
        public int TrackingContactId { get; set; }
        public Nullable<int> TrackingProviderSpecificId { get; set; }
        public string ContactName { get; set; }
        public string ContactSurname { get; set; }
        public string ContactCell { get; set; }
        public int ContactRelationship { get; set; }
        public int ContactTitle { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsPublished { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
        public Nullable<System.DateTime> UpdatedOnDate { get; set; }
    
        public virtual TrackingProviderSpecific TrackingProviderSpecific { get; set; }
    }
}
