//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackingProviderSpecific
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrackingProviderSpecific()
        {
            this.TrackingProviderContacts = new HashSet<TrackingProviderContact>();
            this.TrackingDrivers = new HashSet<TrackingDriver>();
        }
    
        public int TrackingProviderSpecificId { get; set; }
        public int OrderItemId { get; set; }
        public bool Insured { get; set; }
        public string Insurer { get; set; }
        public decimal MonthlyPremium { get; set; }
        public int ModelId { get; set; }
        public string RegistrationNumber { get; set; }
        public int FitmentCentreId { get; set; }
        public System.DateTime FitmentDate { get; set; }
        public bool DifferentDriver { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsPublished { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
        public Nullable<System.DateTime> UpdatedOnDate { get; set; }
    
        public virtual FitmentCentre FitmentCentre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrackingProviderContact> TrackingProviderContacts { get; set; }
        public virtual OrderItem OrderItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrackingDriver> TrackingDrivers { get; set; }
    }
}
