//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransUnionHistory
    {
        public int TransUnionHistoryId { get; set; }
        public int CustomerId { get; set; }
        public System.DateTime VettingDate { get; set; }
        public string VettingOutCome { get; set; }
        public string VettingReasons { get; set; }
        public string VettingStatus { get; set; }
        public Nullable<decimal> BCCScore { get; set; }
        public Nullable<decimal> OTB { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
