//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.CampaignLeadExclusions = new HashSet<CampaignLeadExclusion>();
            this.CampaignVerifiers = new HashSet<CampaignVerifier>();
            this.Customers = new HashSet<Customer>();
            this.CustomerAnnotations = new HashSet<CustomerAnnotation>();
            this.CustomerComs = new HashSet<CustomerCom>();
            this.InstantAVSChecks = new HashSet<InstantAVSCheck>();
            this.NonSalesCustomers = new HashSet<NonSalesCustomer>();
            this.SMSSents = new HashSet<SMSSent>();
            this.AgentOrderStatusDetailMappings = new HashSet<AgentOrderStatusDetailMapping>();
            this.AvsrHistories = new HashSet<AvsrHistory>();
            this.CCQueries = new HashSet<CCQuery>();
            this.CommunicationTemplates = new HashSet<CommunicationTemplate>();
            this.SmsBulkUploadFiles = new HashSet<SmsBulkUploadFile>();
            this.BulkDealUploads = new HashSet<BulkDealUpload>();
            this.ProviderVouchers = new HashSet<ProviderVoucher>();
            this.DialerLeads = new HashSet<DialerLead>();
            this.Leads = new HashSet<Lead>();
            this.Leads1 = new HashSet<Lead>();
            this.LeadBatches = new HashSet<LeadBatch>();
            this.LeadStatusHistories = new HashSet<LeadStatusHistory>();
            this.LeadUploadFormats = new HashSet<LeadUploadFormat>();
            this.BulkStatusFileUploads = new HashSet<BulkStatusFileUpload>();
            this.Orders = new HashSet<Order>();
            this.Orders1 = new HashSet<Order>();
            this.Orders2 = new HashSet<Order>();
            this.OrderAnnotations = new HashSet<OrderAnnotation>();
            this.OrderBundles = new HashSet<OrderBundle>();
            this.OrderBundles1 = new HashSet<OrderBundle>();
            this.OrderItems = new HashSet<OrderItem>();
            this.OrderItemVettingResults = new HashSet<OrderItemVettingResult>();
            this.OrderProviderStatusCommsTemplateHistories = new HashSet<OrderProviderStatusCommsTemplateHistory>();
            this.OrderStatusHistories = new HashSet<OrderStatusHistory>();
            this.WholesaleFileUploads = new HashSet<WholesaleFileUpload>();
            this.QAForms = new HashSet<QAForm>();
            this.QAProgresses = new HashSet<QAProgress>();
            this.StockInvoices = new HashSet<StockInvoice>();
            this.SaleReferralMappings = new HashSet<SaleReferralMapping>();
            this.Teams = new HashSet<Team>();
            this.Tokens = new HashSet<Token>();
            this.User1 = new HashSet<User>();
            this.UserCampaignMappings = new HashSet<UserCampaignMapping>();
            this.UserInRoles = new HashSet<UserInRole>();
            this.UserQualities = new HashSet<UserQuality>();
            this.User11 = new HashSet<User>();
        }
    
        public int UserID { get; set; }
        public int CompanyId { get; set; }
        public bool Active { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public int TitleId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string IdNumber { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Tel3 { get; set; }
        public string Tel4 { get; set; }
        public string Email { get; set; }
        public string Comments { get; set; }
        public Nullable<int> UserTypeId { get; set; }
        public Nullable<int> TeamId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public bool Verifier { get; set; }
        public bool VettingOverride { get; set; }
        public Nullable<int> TeamPositionId { get; set; }
        public int QARatio { get; set; }
        public Nullable<int> OTP { get; set; }
        public bool SysAdmin { get; set; }
        public Nullable<int> OldEMId { get; set; }
        public Nullable<int> OldMsId { get; set; }
        public Nullable<int> TeamLeaderId { get; set; }
        public Nullable<int> CampaignManagerId { get; set; }
        public Nullable<int> NonSalesQARatio { get; set; }
        public Nullable<int> SupervisorQARatio { get; set; }
        public Nullable<int> AuditQARatio { get; set; }
        public Nullable<System.DateTime> QAOverrideEndDate { get; set; }
        public Nullable<int> EmployeeNumber { get; set; }
        public bool IsWhamFeed { get; set; }
        public string AgentDialerId { get; set; }
        public Nullable<int> ExtraLeads { get; set; }
        public Nullable<System.DateTime> ExtraLeadsResetDate { get; set; }
        public bool FAIS { get; set; }
        public Nullable<int> CURId { get; set; }
        public Nullable<System.DateTime> EmployeeStartDate { get; set; }
        public Nullable<System.DateTime> EmployeeGroupStartDate { get; set; }
        public Nullable<System.DateTime> EmployeeTerminationDate { get; set; }
        public Nullable<System.DateTime> LastLoggedInDate { get; set; }
    
        public virtual Title Title { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampaignLeadExclusion> CampaignLeadExclusions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampaignVerifier> CampaignVerifiers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerAnnotation> CustomerAnnotations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerCom> CustomerComs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstantAVSCheck> InstantAVSChecks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NonSalesCustomer> NonSalesCustomers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMSSent> SMSSents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgentOrderStatusDetailMapping> AgentOrderStatusDetailMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvsrHistory> AvsrHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CCQuery> CCQueries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommunicationTemplate> CommunicationTemplates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SmsBulkUploadFile> SmsBulkUploadFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BulkDealUpload> BulkDealUploads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProviderVoucher> ProviderVouchers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DialerLead> DialerLeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lead> Leads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lead> Leads1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeadBatch> LeadBatches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeadStatusHistory> LeadStatusHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeadUploadFormat> LeadUploadFormats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BulkStatusFileUpload> BulkStatusFileUploads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderAnnotation> OrderAnnotations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderBundle> OrderBundles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderBundle> OrderBundles1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItemVettingResult> OrderItemVettingResults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProviderStatusCommsTemplateHistory> OrderProviderStatusCommsTemplateHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderStatusHistory> OrderStatusHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WholesaleFileUpload> WholesaleFileUploads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QAForm> QAForms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QAProgress> QAProgresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockInvoice> StockInvoices { get; set; }
        public virtual Company Company { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleReferralMapping> SaleReferralMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Team> Teams { get; set; }
        public virtual Team Team { get; set; }
        public virtual TeamPosition TeamPosition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Token> Tokens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> User1 { get; set; }
        public virtual User User2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserCampaignMapping> UserCampaignMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserInRole> UserInRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserQuality> UserQualities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> User11 { get; set; }
        public virtual User User3 { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
