//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VASDuplicateMapping
    {
        public int VasDuplicateId { get; set; }
        public int OrderTypeId { get; set; }
        public int OrderStatusId { get; set; }
        public int OrderStatusDetailId { get; set; }
        public int CreatedByUserID { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public int IsDeleted { get; set; }
        public int IsPublished { get; set; }
        public Nullable<int> UpdatedByUserID { get; set; }
        public Nullable<int> UpdatedOnDate { get; set; }
    }
}
