//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleProviderSpecificDetail
    {
        public int VehicleProviderSpecificDetailsId { get; set; }
        public int OrderItemId { get; set; }
        public int VehicleMake { get; set; }
        public int VehicleModel { get; set; }
        public string Registration { get; set; }
        public string Colour { get; set; }
        public string VehicleYear { get; set; }
    
        public virtual VehicleMake VehicleMake1 { get; set; }
        public virtual VehicleModel VehicleModel1 { get; set; }
        public virtual OrderItem OrderItem { get; set; }
    }
}
