//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VettingHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VettingHistory()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int VettingHistoryId { get; set; }
        public string CustomerIDNumber { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public int VettingTypeId { get; set; }
        public string VettingOutcome { get; set; }
        public string VettingStatus { get; set; }
        public Nullable<decimal> VettingOTB { get; set; }
        public Nullable<decimal> VettingScore { get; set; }
        public string ExtraData { get; set; }
        public Nullable<int> CustomerLeadId { get; set; }
    
        public virtual VettingType VettingType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
