//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VettingSetting
    {
        public int VettingSettingsId { get; set; }
        public string Title { get; set; }
        public int CampaignID { get; set; }
        public int VettingTypeID { get; set; }
        public Nullable<decimal> MinimumVet { get; set; }
        public Nullable<int> DealPercentage { get; set; }
        public Nullable<bool> WorkflowVetting { get; set; }
        public Nullable<bool> InboundVetting { get; set; }
        public Nullable<bool> TeamLeadOverride { get; set; }
        public Nullable<bool> ArchiveVetting { get; set; }
        public Nullable<int> ArchivePeriod { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
        public Nullable<System.DateTime> UpdatedOnDate { get; set; }
        public bool IsPublished { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Campaign Campaign { get; set; }
        public virtual VettingType VettingType { get; set; }
    }
}
