//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        public int VoucherID { get; set; }
        public string Code { get; set; }
        public Nullable<int> OrderItemId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UseDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<int> VoucherTypeId { get; set; }
        public string S1S2 { get; set; }
        public string S3 { get; set; }
        public string Cell { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public Nullable<int> BrandId { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual OrderItem OrderItem { get; set; }
        public virtual VoucherType VoucherType { get; set; }
    }
}
