//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwBCCT
    {
        public int SalesAgentID { get; set; }
        public string SalesAgent { get; set; }
        public Nullable<int> TeamID { get; set; }
        public string TeamName { get; set; }
        public Nullable<int> TeamLeaderUserTypeID { get; set; }
        public Nullable<int> TeamLeaderID { get; set; }
        public string TeamLeaderName { get; set; }
        public Nullable<int> UserTypeID { get; set; }
        public Nullable<int> CampaignID { get; set; }
        public string CampaignTitle { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string CompanyTitle { get; set; }
        public Nullable<int> BrandID { get; set; }
        public string BrandTitle { get; set; }
    }
}
