//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwGetProductByManualInvoice
    {
        public int productID { get; set; }
        public string Title { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int ManualInvoiceID { get; set; }
        public string CategoryTitle { get; set; }
        public string ManufacturerTitle { get; set; }
    }
}
