//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwGetDispatchOrdersNew
    {
        public int OrderID { get; set; }
        public int OrderItemID { get; set; }
        public int BrandID { get; set; }
        public string StatusText { get; set; }
        public int OrderStatusDetailID { get; set; }
        public string StatusDetailText { get; set; }
        public string CampaignTitle { get; set; }
        public string IdNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string OrderTypeTitle { get; set; }
        public string OrderReference { get; set; }
    }
}
