//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwGetMovementOrder
    {
        public string IMEI { get; set; }
        public int stockitemID { get; set; }
        public Nullable<int> BrandID { get; set; }
        public string BrandTitle { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string OrderStatusText { get; set; }
        public string OrderStatusDetailText { get; set; }
        public string Product { get; set; }
        public Nullable<int> StockStatusID { get; set; }
        public string StockStatusTitle { get; set; }
        public string OrderRef { get; set; }
    }
}
