//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwGetStockDetail
    {
        public string IMEI { get; set; }
        public string StockStatus { get; set; }
        public int ProductID { get; set; }
        public string ProductTitle { get; set; }
        public int PONumber { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<int> OrderItemID { get; set; }
    }
}
