//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwGetManualInvDetail
    {
        public int ManualInvoiceID { get; set; }
        public string ManualInvoiceType { get; set; }
        public string CompanyName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string IDNumber { get; set; }
        public string Telephone1 { get; set; }
        public string Telephone2 { get; set; }
        public string Notes { get; set; }
        public string InternalNotes { get; set; }
        public string DispatchType { get; set; }
        public string Waybill { get; set; }
        public string IMEI { get; set; }
        public string BrandTitle { get; set; }
    }
}
