//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwGetConsignData
    {
        public string OrderReference { get; set; }
        public int OrderItemID { get; set; }
        public int BrandID { get; set; }
        public string Title { get; set; }
        public int OrderID { get; set; }
        public string Category { get; set; }
        public int OrderTypeID { get; set; }
    }
}
