//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwGetSaleReferralList
    {
        public int SaleReferralListID { get; set; }
        public int QAAgentID { get; set; }
        public Nullable<int> QAID { get; set; }
        public int TeamLeadID { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public int Status { get; set; }
        public string TeamLead { get; set; }
        public string SalesAgent { get; set; }
        public string QAAgent { get; set; }
        public int CustomerID { get; set; }
    }
}
