//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwGetFraudCheckOrderItem
    {
        public int OrderItemID { get; set; }
        public int OrderTypeID { get; set; }
        public string IdNumber { get; set; }
        public string AccountNumber { get; set; }
        public string Contact { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int OrderID { get; set; }
        public Nullable<int> CancelStatusDetailID { get; set; }
    }
}
