//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwIndexDeal
    {
        public int DealID { get; set; }
        public string DealTitle { get; set; }
        public string DealCode { get; set; }
        public string Campaign { get; set; }
        public string Provider { get; set; }
    }
}
