//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwIndexVoucher
    {
        public int VoucherID { get; set; }
        public string VoucherCode { get; set; }
        public Nullable<System.DateTime> VoucherCreateDate { get; set; }
        public Nullable<System.DateTime> VoucherUseDate { get; set; }
        public Nullable<System.DateTime> VoucherExpiryDate { get; set; }
    }
}
