//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwIndexCompany
    {
        public int CompanyID { get; set; }
        public string CompanyTitle { get; set; }
        public string CompanyPhysicalAddress { get; set; }
        public string CompanyPostalAddress { get; set; }
        public string CompanyTelephone { get; set; }
        public string CompanyFacsimile { get; set; }
        public string CompanyVATNo { get; set; }
        public string CompanyRegNo { get; set; }
    }
}
