//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwIndexOrderItem
    {
        public int OrderID { get; set; }
        public int OrderItemID { get; set; }
        public int OrderItemOrderStatusDetailID { get; set; }
        public int DealID { get; set; }
        public string DealDescription { get; set; }
        public int ProductID { get; set; }
        public string ProductDescription { get; set; }
        public int TariffID { get; set; }
        public string TariffDescription { get; set; }
    }
}
