//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwIndexLeadBatch
    {
        public Nullable<long> RowIX { get; set; }
        public Nullable<long> CBIGNORE { get; set; }
        public int LeadBatchID { get; set; }
        public System.DateTime LeadBatchUploadDate { get; set; }
        public string LeadBatchReference { get; set; }
        public int UserID { get; set; }
        public string UserUserName { get; set; }
        public int CampaignID { get; set; }
        public string CampaignTitle { get; set; }
    }
}
