//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwIndexOrderStatu
    {
        public int OrderStatusID { get; set; }
        public string OrderStatusText { get; set; }
        public int OrderStatusDetailID { get; set; }
        public string OrderStatusDetailText { get; set; }
    }
}
