//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwIndexDNCWithBrandTitle
    {
        public int DNCID { get; set; }
        public string BrandTitle { get; set; }
        public string ContactNumber { get; set; }
        public int BrandID { get; set; }
        public string IDNumber { get; set; }
    }
}
