//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwIndexOrder
    {
        public int OrderID { get; set; }
        public string BasketReference { get; set; }
        public int CustomerID { get; set; }
        public string CustomerFirstName { get; set; }
        public string CustomerLastName { get; set; }
        public string CustomerEmail { get; set; }
        public string CustomerMobile { get; set; }
        public string CustomerIDNumber { get; set; }
        public string CustomerAddressCompany { get; set; }
        public string CustomerAddressBuilding { get; set; }
        public string CustomerAddressStreetNum { get; set; }
        public string CustomerAddressStreetName { get; set; }
        public string CustomerAddressSuburb { get; set; }
        public string CustomerAddressPostCode { get; set; }
        public int CityID { get; set; }
        public string CityName { get; set; }
        public int ProvinceID { get; set; }
        public string ProvinceName { get; set; }
        public int CountryID { get; set; }
        public string CountryName { get; set; }
        public int UserID { get; set; }
        public string UserUserName { get; set; }
    }
}
