//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwIndexQAForm
    {
        public int QAFormID { get; set; }
        public System.DateTime QAFormFormDate { get; set; }
        public int OrderID { get; set; }
        public int QAQuestionTypeID { get; set; }
        public string QAQuestionTypeName { get; set; }
    }
}
