//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwIndexFraudulentCredential
    {
        public int FraudulentCredentialID { get; set; }
        public string FraudulentCredentialContactNumber { get; set; }
        public string FraudulentCredentialBankAccountNumber { get; set; }
        public string FraudulentCredentialIDNumber { get; set; }
        public string FraudulentCredentialAddress { get; set; }
    }
}
