//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwIndexProduct
    {
        public int ProductID { get; set; }
        public string ProductBarcode { get; set; }
        public int ProductActive { get; set; }
        public string ProductTitle { get; set; }
        public string ProductDescription { get; set; }
        public string ProductWriteUp { get; set; }
        public int ManufacturerID { get; set; }
        public string ManufacturerName { get; set; }
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
    }
}
