//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwIndexSMSInbox
    {
        public int SMSInboxID { get; set; }
        public string SMSInboxMobileNumber { get; set; }
        public string SMSInboxMessage { get; set; }
        public System.DateTime SMSInboxDateAdded { get; set; }
    }
}
