//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwLeadStatusWithDetail
    {
        public int LeadStatusID { get; set; }
        public int LeadStatusDetailID { get; set; }
        public string Title { get; set; }
        public string LeadStatusDetailText { get; set; }
        public string StatusWithDetailText { get; set; }
    }
}
