//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwLeadsDisposition
    {
        public string Mobile_Number { get; set; }
        public string ID_Number { get; set; }
        public string Order_Reference { get; set; }
        public string Code { get; set; }
        public string Lead_Status { get; set; }
        public string Lead_Status_Detail { get; set; }
        public string Campaign_Name { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
