//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwQAResponse
    {
        public int QAResponseID { get; set; }
        public int QAFormID { get; set; }
        public int QAQuestionID { get; set; }
        public int QASectionId { get; set; }
        public string QAQuestionQuestion { get; set; }
        public decimal QuestionWeight { get; set; }
        public string QAResponseComment { get; set; }
        public decimal QAResponseScore { get; set; }
    }
}
