//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwReportSummaryStatu
    {
        public System.DateTime OrderDate { get; set; }
        public string StatusText { get; set; }
        public string StatusDetailText { get; set; }
        public Nullable<int> num { get; set; }
        public int holding { get; set; }
        public int cancelling { get; set; }
    }
}
