//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwReportNonQaAgent
    {
        public int FormID { get; set; }
        public string StatusTitle { get; set; }
        public System.DateTime FormDate { get; set; }
        public string SalesAgent { get; set; }
        public string QAAgent { get; set; }
        public int OrderID { get; set; }
        public int QAQuestionTypeId { get; set; }
        public int FormTypeID { get; set; }
    }
}
