//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwReportLowScoreAverage70To75
    {
        public Nullable<int> Count { get; set; }
        public System.DateTime FormDate { get; set; }
        public decimal Score { get; set; }
    }
}
