//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwReportDailyQa
    {
        public int QAFormID { get; set; }
        public string SalesAgent { get; set; }
        public string TeamLeader { get; set; }
        public string QAAgent { get; set; }
        public string Title { get; set; }
        public string StatusTitle { get; set; }
        public decimal Score { get; set; }
        public string FirstName { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public string OrderReference { get; set; }
    }
}
