//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwReportGetTeamLeader
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public int TeamID { get; set; }
        public string TeamName { get; set; }
        public int UserTypeID { get; set; }
        public string UserTypeName { get; set; }
    }
}
