//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwReportReactiveSummary
    {
        public Nullable<System.DateTime> RequestDate { get; set; }
        public string Reason { get; set; }
        public string Company { get; set; }
        public string Campaign { get; set; }
        public Nullable<int> CNT { get; set; }
        public string CCQAAgent { get; set; }
        public string TeamLeader { get; set; }
    }
}
