//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwStockSchema
    {
        public int ManufacturerID { get; set; }
        public string Name { get; set; }
        public int Expr1 { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string WriteUp { get; set; }
        public int Active { get; set; }
        public Nullable<decimal> StockCount { get; set; }
        public string Barcode { get; set; }
        public int CategoryID { get; set; }
        public decimal Price { get; set; }
        public int Expr2 { get; set; }
        public string Category { get; set; }
        public int Expr3 { get; set; }
        public int ProductID { get; set; }
        public byte[] Picture { get; set; }
        public byte[] Thumbnail { get; set; }
        public int Expr4 { get; set; }
        public string InvoiceNo { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int UserID { get; set; }
        public string SupplierInvoiceNo { get; set; }
        public int StockPurchaseOrderID { get; set; }
        public int Expr5 { get; set; }
        public string SerialNumber { get; set; }
        public string Pin { get; set; }
        public decimal Expr6 { get; set; }
        public Nullable<int> Expr7 { get; set; }
        public Nullable<int> StockInvoiceID { get; set; }
        public int Expr8 { get; set; }
        public Nullable<int> ReturnStatus { get; set; }
        public Nullable<int> BrandID { get; set; }
        public string SIM { get; set; }
        public int Expr9 { get; set; }
        public System.DateTime OccuredOn { get; set; }
        public int StockItemID { get; set; }
        public int OrderItemDataID { get; set; }
        public string Comment { get; set; }
        public int Expr10 { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> PONumber { get; set; }
        public Nullable<int> ItemCount { get; set; }
        public Nullable<byte> Closed { get; set; }
        public Nullable<System.DateTime> Expr11 { get; set; }
        public Nullable<int> Expr12 { get; set; }
        public int Expr13 { get; set; }
        public int Expr14 { get; set; }
        public int Expr15 { get; set; }
        public int Quantity { get; set; }
    }
}
