//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwSupplierSchema
    {
        public int SupplierID { get; set; }
        public int SupplierTypeID { get; set; }
        public string Name { get; set; }
        public int Expr1 { get; set; }
        public int BranchCodeID { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<int> AccountTypeID { get; set; }
        public int Expr2 { get; set; }
        public int Expr3 { get; set; }
        public int Expr4 { get; set; }
        public string SupplierBankName { get; set; }
        public int Expr5 { get; set; }
        public int Expr6 { get; set; }
        public int BrandID { get; set; }
        public int Expr7 { get; set; }
        public int Expr8 { get; set; }
        public int EmployeeIndustryID { get; set; }
        public int Expr9 { get; set; }
        public int Expr10 { get; set; }
        public int PostCode { get; set; }
        public int Expr11 { get; set; }
        public string SupplierType { get; set; }
    }
}
