//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WholesaleFileUpload
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WholesaleFileUpload()
        {
            this.WholesaleFileUploadContents = new HashSet<WholesaleFileUploadContent>();
        }
    
        public int WholesaleFileUploadId { get; set; }
        public System.DateTime UploadDate { get; set; }
        public string Filename { get; set; }
        public int UserId { get; set; }
        public bool CheckFile { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
        public Nullable<System.DateTime> UpdatedOnDate { get; set; }
        public bool IsPublished { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> TotalUploaded { get; set; }
        public Nullable<int> TotalFailed { get; set; }
        public Nullable<int> TotalSuccessful_ { get; set; }
        public Nullable<int> ProviderId { get; set; }
        public Nullable<bool> HasItems { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WholesaleFileUploadContent> WholesaleFileUploadContents { get; set; }
        public virtual User User { get; set; }
    }
}
