//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approach1.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WholesaleFileUploadContent
    {
        public int WholesaleFileUploadContentsId { get; set; }
        public int WholesaleFIleUploadId { get; set; }
        public string Firstname { get; set; }
        public string Surname { get; set; }
        public string IDNumber { get; set; }
        public string MSISDN { get; set; }
        public string Email { get; set; }
        public int PartnerId { get; set; }
        public string OrderType { get; set; }
        public string Package { get; set; }
        public System.DateTime ChangeStatusDate { get; set; }
        public string Status { get; set; }
        public string Reason { get; set; }
        public bool Execute { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
        public Nullable<System.DateTime> UpdatedOnDate { get; set; }
        public bool IsPublished { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual WholesaleFileUpload WholesaleFileUpload { get; set; }
    }
}
